import Head from "next/head";
import Image from "next/image";
import R2E from "../public/R2E.png";
import CountdownTimer from "../components/CountdownTimer";
import {
	Box,
	Flex,
	WrapItem,
	VStack,
	Button,
	Center,
	Wrap,
	Grid,
	SimpleGrid,
	GridItem,
} from "@chakra-ui/react";
import PriceTable from "../components/PriceTable";
import { useBreakpointValue } from "@chakra-ui/react";

export default function Home() {
	const THREE_DAYS_IN_MS = 3 * 24 * 60 * 60 * 1000;
	const NOW_IN_MS = new Date().getTime();

	const dateTimeAfterThreeDays = NOW_IN_MS + THREE_DAYS_IN_MS;

	const direction = useBreakpointValue({ md: "row", base: "column" });
	const imageSize = useBreakpointValue({ md: "cover", base: "contain" });

	return (
		<>
			<Head>
				<title>Project Empower</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<h2>
				a Local Community Involvement Project (LCIP) under NUS Medical Society
				that aims to empower caregivers
			</h2>

			<Flex flexDirection={direction} alignItems="center" mx="auto">
				<Box minW="60vw">
					<Image src={R2E} alt="1" layout="responsive" />
				</Box>
				<Box display="flex" flexDirection="column" alignItems="center">
					<CountdownTimer targetDate={dateTimeAfterThreeDays} />
					<Box>
						<h3>What are you waiting for? Sign Up Now!</h3>
					</Box>
					<Button>Sign Up!</Button>
				</Box>
			</Flex>
			<PriceTable />
		</>
	);
}
